### ISSUE TITLE
Exploring Jhipster?

### ISSUE THREAD

**Issue by fagossa** [zathuracode/zathuracode-generator#2]
Hi,
I don't know if you are aware of [jhipster](https://jhipster.github.io/), but it could be a nice alternative to consider.

Thanks to [springboot](http://projects.spring.io/spring-boot/) the code generated could be executed as a stand alone app which means no app server :)

**Comment by zathuracode** [comment]
Si es una buena herramienta ya la revisamos.

Muchas gracias.
